# SPDX-License-Identifier: GPL-3.0
#
# Shared CMake glue for the Meshtastic test suites.

set(MESHTASTIC_TEST_COMMON_DIR ${CMAKE_CURRENT_LIST_DIR})

# Give the test app access to the stack's private headers and to the nanopb
# sources generated by the module build.
macro(meshtastic_test_setup)
  target_include_directories(app PRIVATE
    ${MESHTASTIC_TEST_COMMON_DIR}
    ${MESHTASTIC_TEST_COMMON_DIR}/../../src
    ${CMAKE_BINARY_DIR}/modules/meshtastic-zephyr/src
    ${CMAKE_BINARY_DIR}/modules/meshtastic-zephyr/src/proto
  )
  # The generated *.pb.h headers only exist once the module library has run its
  # nanopb steps, so make that ordering explicit.
  if(TARGET meshtastic)
    add_dependencies(app meshtastic)
  endif()
endmacro()

# Link in the mock LoRa transceiver used by the radio-level suites.
macro(meshtastic_test_use_mock_lora)
  target_sources(app PRIVATE ${MESHTASTIC_TEST_COMMON_DIR}/mock_lora.c)
endmacro()
